[package]
name = "trender"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
serde_json = "1.0"
crossterm = "0.22.0"
terminal_size = "0.3.0"
